<a href="https://colab.research.google.com/github/ashwin-rema/Machine-Learning/blob/main/Digital%20digit%20recognition%20model/ML_MAJOR_MAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df = pd.read_csv('digit_svm.csv')
df

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0          1       0       0       0  ...         0         0         0         0
1          0       0       0       0  ...         0         0         0         0
2          1       0       0       0  ...         0         0         0         0
3          4       0       0       0  ...         0         0         0         0
4          0       0       0       0  ...         0         0         0         0
...      ...     ...     ...     ...  ...       ...       ...       ...       ...
41995      0       0       0       0  ...         0         0         0         0
41996      1       0       0       0  ...         0         0         0         0
41997      7       0       0       0  ...         0         0         0         0
41998      6       0       0       0  ...         0         0         0         0
41999      9       0       0       0  ...         0         0         0         0

[42000 rows x 785 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [ ]:
df.describe()

label   pixel0   pixel1  ...  pixel781  pixel782  pixel783
count  42000.000000  42000.0  42000.0  ...   42000.0   42000.0   42000.0
mean       4.456643      0.0      0.0  ...       0.0       0.0       0.0
std        2.887730      0.0      0.0  ...       0.0       0.0       0.0
min        0.000000      0.0      0.0  ...       0.0       0.0       0.0
25%        2.000000      0.0      0.0  ...       0.0       0.0       0.0
50%        4.000000      0.0      0.0  ...       0.0       0.0       0.0
75%        7.000000      0.0      0.0  ...       0.0       0.0       0.0
max        9.000000      0.0      0.0  ...       0.0       0.0       0.0

[8 rows x 785 columns]

In [ ]:
df.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [ ]:
x = df.iloc[:,1:785].values
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y = df['label'].values
y

array([1, 0, 1, ..., 7, 6, 9])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size = 0.3 , random_state = 0)

In [ ]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y_train

array([0, 1, 9, ..., 9, 0, 9])

In [ ]:
from sklearn.svm import SVC

In [ ]:
classifier = SVC( kernel = "linear" ,random_state = 0)

In [ ]:
classifier.fit(x_train,y_train)

In [ ]:
y_pred = classifier.predict(x_test)
y_pred

array([3, 6, 9, ..., 1, 6, 5])

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score

In [ ]:
confusion_matrix(y_test , y_pred)

array([[1225,    0,    2,    0,    2,    3,    6,    0,    4,    0],
       [   0, 1409,    7,    3,    1,    0,    2,    1,    5,    1],
       [   3,    0, 1250,    3,    3,    1,    0,    8,    7,    1],
       [   1,    2,   12, 1243,    1,   15,    2,    5,   13,    4],
       [   1,    4,    2,    0, 1202,    1,    4,    2,    0,   20],
       [   1,    0,    3,    7,    1, 1093,    9,    0,    2,    3],
       [   7,    0,    0,    0,    3,    6, 1225,    0,    2,    0],
       [   2,    5,    8,    2,    9,    2,    0, 1288,    4,   14],
       [   2,    9,    3,    8,    3,    6,    5,    0, 1165,    3],
       [   7,    2,    3,    7,   10,    2,    0,   13,    2, 1173]])

In [ ]:
accuracy_score(y_test , y_pred)

0.974047619047619